apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #the PV is not automatically deleted when the PVC is removed

  storageClassName: standard
  # Automatically creates PersistentVolumes (PVs) when a PersistentVolumeClaim (PVC) is made

  #storageClassName: manual
  # Requires administrators to manually create PVs before they can be bound to PVCs. The PVs must explicitly match the `storageClassName` of the PVC

  hostPath:
    path: /mnt/data/redis # on the minikube host


